
  name: Output Event Details on "issues"
  on: issues
  jobs:
    output:
        runs-on: ubuntu-latest
        steps:
          - name: Output details
            run: echo "${{toJson(github.event)}}"
          